blueprint:
  name: Groupe dynamique d'équipements
  description: |
    Ce blueprint crée des groupes d'équipements dynamiques, les maintient à jour chaque heure,
    permet de spécifier le nom et la description des groupes, de générer une liste déroulante des types d'équipements disponibles,
    et d'utiliser des mots-clés pour inclure ou exclure des équipements, ainsi que d'ajouter des équipements manuellement.
  domain: automation
  input:
    group_name:
      name: Dynamic Group Name
      description: Le nom du groupe d'équipements à créer
      selector:
        text:
      default: dynamic_group
    group_description:
      name: This is the description of the dynamic group
      description: La description du groupe d'équipements à créer
      selector:
        text
    device_domains:
      name: Dynamic Domain List Available
      description: Liste des types d'équipements disponibles (Domain)
      selector:
        select:
          options:
            - "light"
            - "switch"
            - "sensor"
            - "binary_sensor"
            - "device_tracker"
            - "media_player"
    include_keywords:
      name: Dynamic Include key word List
      description: Liste de mots-clés pour inclure les équipements
      selector:
        text:
          multiline: true
    exclude_keywords:
      name: Dynamic key word to exclude from the list
      description: Liste de mots-clés pour exclure les équipements
      selector:
        text:
          multiline: true
    manual_include:
      name: Add manual devices list to include
      description: Liste des équipements à inclure manuellement
      selector:
        entity:
          multiple: true
    manual_exclude:
      name: Add manual devices list to exclude
      description: Liste des équipements à exclure manuellement
      selector:
        entity:
          multiple: true

trigger:
  - platform: time_pattern
    hours: "/1"

variables:
  include_list: !input include_keywords
  exclude_list: !input exclude_keywords
  domains: !input device_domains
  manual_include: !input manual_include
  manual_exclude: !input manual_exclude
  entities: "{{ states | selectattr('domain','in',domains.split('\n')) | map(attribute='entity_id') | list }}"

condition: "{{ (any_include(entity, include_list) or entity in manual_include) and not (any_exclude(entity, exclude_list) or entity in manual_exclude) }}"

action:
  - service: group.set
    data:
      object_id: !input 'group_name'
      name: !input 'group_name'
      description: !input 'group_description'
      entities: "{{ entities | select('any_include') | reject('any_exclude') | list }}"
      icon: mdi:devices

template:
  any_include: >
    {% for keyword in include_list.split('\n') %}
    {% if keyword in entity %}true{% endif %}
    {% endfor %}
    false

  any_exclude: >
    {% for keyword in exclude_list.split('\n') %}
    {% if keyword in entity %}true{% endif %}
    {% endfor %}
    false
