blueprint:
  name: Groupe dynamique d'équipements
  description: |
    Ce blueprint crée des groupes d'équipements dynamiques, les maintient à jour chaque heure,
    permet de spécifier le nom, l'ID, et la pièce des groupes, de générer une liste déroulante des types d'équipements disponibles,
    et d'utiliser des mots-clés pour inclure ou exclure des équipements, ainsi que d'ajouter des équipements manuellement.
  domain: automation
  input:
    group_name:
      name: Dynamic Group Name
      description: Le nom du groupe d'équipements à créer
      selector:
        text: {}
      default: "Dynamic Group Name"
    group_id:
      name: Dynamic Group ID
      description: L'ID du groupe d'équipements à créer
      selector:
        text: {}
      default: "dynamic_group_name"
    group_room:
      name: Room Assignment
      description: La pièce assignée au groupe d'équipements
      selector:
        area: {}
    group_description:
      name: Description du groupe
      description: La description du groupe d'équipements à créer
      selector:
        text: {}
      default: "This is the description of the dynamic group"
    device_domains:
      name: Dynamic Domain List Available
      description: Liste des types d'équipements disponibles (Domain)
      selector:
        select:
          options:
            - "light"
            - "switch"
            - "sensor"
            - "binary_sensor"
            - "device_tracker"
            - "media_player"
      default: "light"
    include_keywords:
      name: Dynamic Include key word List
      description: Liste de mots-clés pour inclure les équipements
      selector:
        text:
          multiline: true
      default: "- "
    exclude_keywords:
      name: Dynamic key word to exclude from the list
      description: Liste de mots-clés pour exclure les équipements
      selector:
        text:
          multiline: true
      default: "- "
    manual_include:
      name: Add manual devices list to include
      description: Liste des équipements à inclure manuellement
      selector:
        entity:
          multiple: true
    manual_exclude:
      name: Add manual devices list to exclude
      description: Liste des équipements à exclure manuellement
      selector:
        entity:
          multiple: true

trigger:
  - platform: time_pattern
    hours: "/1"

action:
  - service: group.set
    data:
      object_id: !input group_id
      name: !input group_name
      description: !input group_description
      entities: >
        {% set include_list = include_keywords.split('\n') %}
        {% set exclude_list = exclude_keywords.split('\n') %}
        {% set domain_list = device_domains %}
        {{ states | selectattr('entity_id', 'in', manual_include) | map(attribute='entity_id') | list + 
           (states | selectattr('entity_id', 'not_in', manual_exclude) | selectattr('domain', 'eq', domain_list) | 
           selectattr('entity_id', 'match', '(' + '|'.join(include_list) + ')') | 
           rejectattr('entity_id', 'match', '(' + '|'.join(exclude_list) + ')') | 
           map(attribute='entity_id') | list) }}
      icon: mdi:devices
      area_id: !input group_room
