blueprint:
  name: Contrôle via Smart Zigbee M1 Switch (4upl1fcj)
  description: "Contrôle des boutons du Smart Zigbee M1 Switch pour activer des actions spécifiques."
  domain: automation
  input:
    zigbee_device:
      name: Interrupteur Zigbee
      description: "Choisissez le Smart Zigbee M1 Switch (4upl1fcj)."
      selector:
        device:
          integration: Tuya
          manufacturer: Tuya
    bouton_1_action:
      name: Action pour le Bouton 1
      description: "Choisissez l'action pour le Bouton 1."
      default: []
      selector:
        action: {}
    bouton_2_action:
      name: Action pour le Bouton 2
      description: "Choisissez l'action pour le Bouton 2."
      default: []
      selector:
        action: {}
    bouton_3_action:
      name: Action pour le Bouton 3
      description: "Choisissez l'action pour le Bouton 3."
      default: []
      selector:
        action: {}
    bouton_4_action:
      name: Action pour le Bouton 4
      description: "Choisissez l'action pour le Bouton 4."
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zigbee_device

action:
  - variables:
      bouton: "{{ trigger.event.data.command }}"
  - choose:
      - conditions:
          - "{{ bouton == 'button_1_click' }}"
        sequence: !input bouton_1_action
      - conditions:
          - "{{ bouton == 'button_2_click' }}"
        sequence: !input bouton_2_action
      - conditions:
          - "{{ bouton == 'button_3_click' }}"
        sequence: !input bouton_3_action
      - conditions:
          - "{{ bouton == 'button_4_click' }}"
        sequence: !input bouton_4_action
